version: '3'

services:
  user_server:
    container_name: user_server
    build:
      context: ./services/user_server
      dockerfile: Dockerfile.Prod
    expose:
      - 5001
    command: uvicorn src.main:app --host 0.0.0.0 --port 5001
    depends_on:
      - db
      - redis

  ml_server:
    container_name: ml_server
    build:
      context: ./services/ml_server
      dockerfile: Dockerfile.Prod
        #    expose:
        #      - 5001
    command: celery --app src.main:app worker --pool=solo -n ml-worker --loglevel=debug --without-mingle --queues=ml_service
    depends_on:
      - redis
        #  client:
        #    container_name: client_apex
        #    build:
        #      context: ./services/client
        #      dockerfile: Dockerfile.Prod
        #    ports:
        #      - 8090:8090
        #    command: nginx
        #    environment:
        #      BASE_URL: /api
        #    depends_on:
        #      - server

  db:
    container_name: sos_database_pg
    image: postgres:16-alpine
    expose:
      - 5432
    environment:
      POSTGRES_USER: fastapi_serv
      POSTGRES_PASSWORD: LGIKLKks87hk65T
      POSTGRES_DB: fastapi_serv_db
    volumes:
      - postgres_pgpool:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    command: redis-server --save 30 1 --loglevel warning
    expose:
      - 6379
    volumes:
      - cache:/data

volumes:
  postgres_pgpool:
  cache:
    driver: local
