version: '3'

services:
  user_server:
    container_name: user_server
    build:
      context: ./services/user_server
      dockerfile: Dockerfile.Prod
        #    environment:
      #      DATABASE_URL: postgres://fastapi_serv:LGIKLKks87hk65T@db:5432/fastapi_serv_db
      #      ROOT_PATH: /api
      #      BASE_URL: http://localhost:8090
      #      DB_HOST: db
      #      DB_PORT: 5432
      #      DB_USER: fastapi_serv
      #      DB_PASSWORD: LGIKLKks87hk65T
      #      DB_NAME: fastapi_serv_db
    expose:
      - 5001
    command: uvicorn src.main:app --host 0.0.0.0 --port 5001
    depends_on:
      - db

        #  client:
        #    container_name: client_apex
        #    build:
        #      context: ./services/client
        #      dockerfile: Dockerfile.Prod
        #    ports:
        #      - 8090:8090
        #    command: nginx
        #    environment:
        #      BASE_URL: /api
        #    depends_on:
        #      - server

  db:
    container_name: sos_database_pg
    image: postgres:16-alpine
    expose:
      - 5432
    environment:
      POSTGRES_USER: fastapi_serv
      POSTGRES_PASSWORD: LGIKLKks87hk65T
      POSTGRES_DB: fastapi_serv_db
    volumes:
      - postgres_pgpool:/var/lib/postgresql/data/

volumes:
  postgres_pgpool:
