version: '3'

services:
  user_server:
    build:
      context: ./services/user_server
      dockerfile: Dockerfile.Dev
    volumes:
      - ./services/user_server/src:/app/src
      - ./services/user_server/environment:/app/environment
      - ./services/user_server/migrations:/app/migrations
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5001
    ports:
      - 5001:5001

  ml_server:
    build:
      context: ./services/ml_server
      dockerfile: Dockerfile.Dev
    volumes:
      - ./services/ml_server/src:/app/src
      - ./services/ml_server/environment:/app/environment

        #  client:
        #    build:
        #      context: ./services/client
        #      dockerfile: Dockerfile.Dev
        #    stdin_open: true
        #    tty: true
        #    volumes:
        #      - './services/client:/app'
        #      - '/usr/src/app/services/client/node_modules'
        #    environment:
        #      BASE_URL: localhost:5001
        #    command: npm run dev

  db:
    environment:
      POSTGRES_USER: fastapi_serv
      POSTGRES_PASSWORD: LGIKLKks87hk65T
      POSTGRES_DB: fastapi_serv_db_debug
    volumes:
      - postgres_pgpool_dev:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 5080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@citizix.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    volumes:
      - pgadmin_data:/home/rundeck/server/data

  redis:
    command: redis-server --save 30 1 --loglevel debug

volumes:
  postgres_pgpool_dev:
  pgadmin_data:
