FROM python:3.11-slim-buster as builder

RUN mkdir app
WORKDIR /app

#ENV PATH="${PATH}:/root/.local/bin"
#ENV PYTHONPATH=./

COPY poetry.lock pyproject.toml ./
RUN pip install --no-cache-dir poetry \
    && poetry config virtualenvs.in-project true \
    && poetry install --without dev --no-interaction --no-ansi

FROM python:3.11-slim-buster

COPY --from=builder /app /app

RUN mkdir -p /var/run/secrets_dir
COPY ./secrets/debug_db_password /var/run/secrets_dir/db_password
COPY ./secrets/debug_jwt_secret /var/run/secrets_dir/jwt_secret

WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PATH="${PATH}:/app/.venv/bin"
#ENV PYTHONPATH=./


