FROM python:3.11-buster as builder

RUN mkdir app
WORKDIR /app

#ENV PATH="${PATH}:/root/.local/bin"
#ENV PYTHONPATH=./

COPY poetry.lock pyproject.toml ./
RUN pip install --no-cache-dir poetry \
    && poetry config virtualenvs.in-project true \
    && poetry install --without dev --no-interaction --no-ansi

FROM python:3.11-buster

COPY --from=builder /app /app

WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PATH="${PATH}:/app/.venv/bin"
#ENV PYTHONPATH=./


